version: "3.8"

services:
  server:
    container_name: server
    restart: always
    build:
      context: ./server
      tags:
        - "connection-broker:latest"
    ports:
      - "6090:6090"
    networks:
      let_me_see_you_net:
        ipv4_address: 192.168.19.13
  ui:
    container_name: ui
    restart: always
    build:
      context: ./ui
      target: ui-webserver
      tags:
        - "letMSU-ui:latest"
    ports:
      - "6091:80"
    networks:
      let_me_see_you_net:
        ipv4_address: 192.168.19.14
  object-storage:
    image: quay.io/minio/minio
    container_name: object-storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio@MINIO
    volumes:
      - ./minio/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      let_me_see_you_net:
        ipv4_address: 192.168.19.15

networks:
  let_me_see_you_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.19.0/24
